name: Node.js CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run build
    - run: npm run lerna -- bootstrap
    - run: npm run lerna run build
      env:
        CI: true
